### ISSUE TITLE
rspec output during adding_matz

### ISSUE THREAD

**Issue by reifnotreef** [learn-co-curriculum/simple-nesting#14]
Below is my terminal copy/pasted.
Inside the first error reported it says "expected [:known_for, :languages] to include :yukihiro_matsumoto" which is not correct. It should be expecting adding_matz to include :yukihiro_matsumoto" like it says in the Failure/Error line.

[// ♥ learn --fail-fast
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

nested hash
  #hopper
    operates on the programmer_hash and returns the value of the :grace_hopper key
  #alan_kay_is_known_for
    operates on the programmer_hash and returns the value of what Alan Kay is known for
  #dennis_ritchies_language
    operates on the programmer_hash and returns the value of Dennis Ritchie's language as a string
  #adding_matz
    operates on the programmer_hash and adds a key/value pair to the top level of the hash, returning the newly-added-to hash (FAILED - 1)

Failures:

  1) nested hash #adding_matz operates on the programmer_hash and adds a key/value pair to the top level of the hash, returning the newly-added-to hash
     Failure/Error: expect(adding_matz.keys).to include(:yukihiro_matsumoto)
     
       expected [:known_for, :languages] to include :yukihiro_matsumoto
       Diff:
       @@ -1,2 +1,2 @@
       -[:yukihiro_matsumoto]
       +[:known_for, :languages]
       
     # ./spec/nested_spec.rb:26:in `block (3 levels) in <top (required)>'

Deprecation Warnings:

RSpec::Core::Configuration#treat_symbols_as_metadata_keys_with_true_values= is deprecated, it is now set to true as default and setting it to false has no effect.

If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 0.01258 seconds (files took 0.08262 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/nested_spec.rb:25 # nested hash #adding_matz operates on the programmer_hash and adds a key/value pair to the top level of the hash, returning the newly-added-to hash

**Comment by vicfriedman** [comment]
Hey @reifnotreef,

The error that you're getting - is comparing what `adding_matz.keys` returned based on your code. When you ran this test and got that error, your code was returning `[:known_for, :languages]`.

It seems like your code passes the tests now, so im going to go ahead and close this issue.

Let me know if you need anything else!
