### ISSUE TITLE
#adding_matz has an inconsistency

### ISSUE THREAD

**Issue by CaninoDev** [learn-co-curriculum/simple-nesting#20]
The comments for #adding_matz state:
```
   # :languages => ["LISP, C"]
```
as a modification to the given hash. Looking at the rest of the hash as given, it should read
```
  # :languages => ["LISP", "C"] 
```
(the languages are separated as a distinct element of array instead of originally being lumped together as one element. And the test should be updated to reflect that.

**Comment by drakeltheryuujin** [comment]
Hi @CaninoDev,

Thank you for your feedback! An update has been made to the lesson text. If you feel that the issue has not been resolved, feel free to reopen the issue.

Thanks 💙
