### ISSUE TITLE
RSPEC - Feedback not accurate

### ISSUE THREAD

**Issue by fbohz** [learn-co-curriculum/simple-nesting#23]
Hello I was working on this lab. I had a problem completing this lab because it required me to return the completed hash not just what I added. However this is the feedback I got:

`TypeError:
       no implicit conversion of Symbol into Integer`

This was not very informative since this is what I had:
`puts programmer_hash[:alan_kay][:known_for]`

and I only needed to return the entire hash:
`puts programmer_hash`

Sorry I submitted this through here but ask a question was not available, was greyed out.

**Comment by drakeltheryuujin** [comment]
Hi @fbohz,

This error shows up when you are treating an array or string as a Hash. However, the instructions do state:
```
Hint: In some of these methods, you will need to alter programmer_hash, then make sure to return the entire hash, not just the altered value.
```
Thanks for the feedback!

**Comment by fbohz** [comment]
I see thanks for the feedback :)
